### PR TITLE
Prepare flatpak for next release

### PR DESCRIPTION
**Pull request by filipestevao**
Hi @narunlifescience 

I have seen many good changes in AlplaPlot. Nice work!

I believe that a next release will be available soon. So, could you merge these changes in flatpak metainfo file before creating a tag? And could you inform the number and date of the next version?

Thanks in advance.

### CODE REVIEW

**Comment by narunlifescience** [comment]
I am planning to stick with 1.02 for the next version. As far as release date is concerned, I am not sure; may be in a month or two. There are some more changes that I would like to introduce in the new version like fixing broken column date time, plot wizard needs to be improved to handle newer plots etc. Also the documentation needs to be prepared which is one of the most important thing to do before release. Please check https://alphaplot.sourceforge.io/wiki/index.php and let me know if you are interested in working with the documentation. Also let me know if you find any bugs in new builds.

I will merge this once the release is about to get ready. Thanks!

**Comment by narunlifescience** [comment]
@filipestevao AlphaPlot is almost ready for the next release. I was thinking of using 1.02 as the new version number for no specific reasons. Do you have any better suggestion ?
Also do let me know of any bugs in the latest build in case I missed something.

**Comment by filipestevao** [comment]
Dear @narunlifescience . I'm following the changes in the project, updating the flatpak beta repository once a week. Also, I'm using the program to make various graphics daily. But because of my work, I'm not putting a lot of effort into AlphaPlot, but I see that you're doing a great job on the project. Congratulations!

One change I might like to make in the future (in a next version perhaps), would be to use QFileDialog to open and import projects. QFileDialog is currently used to save AlphaPlot projects and uses flatpak [portals](https://github.com/flatpak/xdg-desktop-portal). That way, you wouldn't need to enable the user's home in the flatpak, making the app more contained and secure. But it's just details.

I think 1.02 is a good new version number and I'll leave this PR enabled for merge.
Again, great job!

**Comment by narunlifescience** [comment]
@filipestevao thanks for the feedback. please change the release date to 18/01/2022

**Pull request merged**
