### PR TITLE
add a 'standard error' computation to TableStatistics.cpp

### PR DESCRIPTION
**Pull request by achjaj**
I added standard error column to TableStatistics.cpp like in QtiPlot. It is a small change but it is useful, at least for me :smiley: .

### CODE REVIEW

**Comment by narunlifescience** [comment]
Hi.. Thanks for the pull request. I will merge it bit later as I am doing some changes locally. (or let me check otherwise)
I am in the process of QT5 port which is almost complete. did you compile the master branch ? new Alpha plot will be using QCustomPlot library for 2d plotting. I will encourage you to compile the latest master branch of AlphaPlot for your suggestions.

**Comment by narunlifescience** [comment]
Hi.. can you give me a fresh request ?

**Comment by achjaj** [comment]
Should I include fix for #12 ?

**Comment by narunlifescience** [comment]
that would be great!

**Comment by narunlifescience** [comment]
Thanks!

**Pull request merged**
