### PR TITLE
Support CMake build system.

### PR DESCRIPTION
**Pull request by ChinouneMehdi**

### CODE REVIEW

**Comment by ChinouneMehdi** [comment]
> Hi... I am not very familiar with CMake so I may have to look at the documentation for the most part of it...

https://cmake.org/cmake/help/latest/manual/cmake-qt.7.html
https://doc.qt.io/qt-5/cmake-manual.html
https://www.qt.io/blog/versionless-cmake-targets-qt-5.15
> but please move all the CMake files to a separate directory. I don't want any files other than source files in src folder. please move them accordingly and then it should be ready to merge.

Sorry, but I can't. This the typical way of working with CMake.
> however, here are some of my concerns:
> 
> 1. It would be better if you incorporate MXE build options.

I don't know MXE.
> 2. did u test CMake build on Mac OS?

No, I don't have access to macos.

**Comment by narunlifescience** [comment]
hmm.. in that case it would be pointless to merge unless the CMake build option may not work on cross-platform. also the CMake files are all over the place which will be hard to manage. I will look in to cmake documentations regarding these issues when I get some free time so that we can work out some better solutions 

I would suggest you look in to https://github.com/narunlifescience/AlphaPlot/wiki/Fix-Me for the things that need to be fixed for the next release.

Alphaplot is also in need of documentation. please have a look at https://alphaplot.sourceforge.io/wiki/ and contribute.

**Comment by narunlifescience** [comment]
I am closing this request as I don't have the time to implement cmake for other platforms & qmake is working well at this point.

**Comment by narunlifescience** [comment]
@ChinouneMehdi  Hey why don't you put all the CMake files in a folder in the root directory and write a bash/batch script file to build the project. you can copy the CMake files to respective directories while building the project using the script. This way we can keep it nice and clean.

I can see that you are working on a workflow. Thanks for the effort.

**Pull request closed without merging**
